version: 2

updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "⬆️"
    groups:
      xunit:
        patterns:
          - "xunit*"
      roslyn:
        patterns:
          - "Microsoft.CodeAnalysis*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "⬆️"
    groups:
      actions:
        patterns:
          - "*"
